// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/triagem-landing/ClinicoTranquilo.tsx": () => import("../components/mockups/triagem-landing/ClinicoTranquilo.tsx"),
  "./components/mockups/triagem-landing/ConversaAcolhedora.tsx": () => import("../components/mockups/triagem-landing/ConversaAcolhedora.tsx"),
  "./components/mockups/triagem-landing/MapaDeCuidado.tsx": () => import("../components/mockups/triagem-landing/MapaDeCuidado.tsx")
};
